# Generated by Django 6.0 on 2026-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('K', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('recommended_crop', models.CharField(max_length=100)),
                ('confidence_score', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='predictionhistory',
            options={},
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='K',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='N',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='P',
            field=models.IntegerField(),
        ),
    ]
